### PR TITLE
Add tests.

### PR DESCRIPTION
**Pull request by satazor**
Based on #14 and #15 but with a few differences:

- Tests do not spawn the cli in a different process; this makes it easy to mock the API and do coverage testing without hassle.
- Use nock to mock requests

What do you think @flesch @rickycodes @mikeerickson
One question though, how can we reliably test if the open command actually open the browser?

### CODE REVIEW

**Comment by satazor** [comment]
Still need to improve the coverage %, it's too low right now.

**Comment by rickycodes** [comment]
@satazor this looks _much_ improved to me 👍

> One question though, how can we reliably test if the open command actually open the browser?

I was wondering about that too...

**Comment by satazor** [comment]
@rickycodes I've figured how to do it, will update this PR in a few minutes.

**Comment by satazor** [comment]
Coverage is now 100%. This is ready to be merged.

**Pull request merged**
