### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by rickycodes**
two simple passing tests:

screen shot 2016-09-07 at 5 39 33 pm

### CODE REVIEW

**Comment by rickycodes** [comment]
I need to clean this up a bit; it also appears that it isn't work in node version 6?

**Comment by rickycodes** [comment]
build fixed 💥  and rebased :)

**Comment by mikeerickson** [comment]
@rickycodes Can you please have a look at the 002 PR once it has been merged to see how I have setup the basic testing framework.  All my tests thus far have been to test CLI actions.

**Comment by rickycodes** [comment]
@flesch @satazor thoughts?

I took some of the notes from #15 and improved my version a bit:

screen shot 2016-09-09 at 12 37 25 pm

**Comment by satazor** [comment]
This colides with #15, need to analyze carefully. I'm on the phone right now.

**Comment by rickycodes** [comment]
@satazor imo this simplifies a lot of things in #15 and is maybe a better starting point...

1. less dependencies (no `chalk`/`trim`)
2. a single `BDD` style using `expect` (vs a mix of `shoud`, `assert`, and `expect`; If we're going for `BDD` we shouldn't be using `assert` at all, aye?)
3. tests are more deterministic:
  - [things like this](https://github.com/npms-io/npms-cli/pull/15/files#diff-7afd14f82c62280583938f8928a81cadR24) are problematic... what happens if results are changed from the current table format in the future?
  - [checking what's returned currently](https://github.com/npms-io/npms-cli/pull/15/files#diff-7afd14f82c62280583938f8928a81cadR75) with `--scoreEffect` is also problematic; presumably this test will fail as scores change/mature.

/cc @mikeerickson 

this was also opened prior to #15

**Comment by mikeerickson** [comment]
@satazor @rickycodes 

I understand what you are saying about your various points of interest.

Further, I believe that eslinting should only be done on the development side (as a pre-commit hook) but not on the travis side.  Would like you input on this item, just don't see linting as a validation for travis.  But if you want it to remain, its your call.

In the meantime, I am going to refactor my tests to use execSync, but if that is too "slow" I will have another stab and use promises

**Comment by mikeerickson** [comment]
@sataroz @rickycodes 

I have updated all my tests to use the same basic construct of what @rickycodes has done.

@satazor Please have a look at the new tests and let me know what else you would like changed

**Comment by rickycodes** [comment]
closing in favour of #16

**Pull request closed without merging**
