### PR TITLE
s -> search and i -> info aliases

### PR DESCRIPTION
**Pull request by larsw**
For convenience, what the title says.

### CODE REVIEW

**Comment by flesch** [comment]
@satazor What do you think? I like `s` but worry `i` could get confused with "install"...

**Comment by mikeerickson** [comment]
@sataroz I agree on the i 

How about `a` for aliases or `n` for info

**Comment by satazor** [comment]
I'm ok with both.

**Comment by satazor** [comment]
@flesch you can merge

**Comment by satazor** [comment]
I actually think i is ok, npms will never have a install command so the confusion is less important..

**Comment by flesch** [comment]
👍  I'll try to push this out tonight.

**Comment by mikeerickson** [comment]
@flesh let me know when you are done and I will pull it down and add the associated tests. Will delay my update w/ all new tests

**Comment by flesch** [comment]
@larsw Is this working for you? `npms s babel` says "`Unknown arguments: s, babel`".

Related to https://github.com/yargs/yargs/issues/121?

**Comment by satazor** [comment]
Apparently yargs does not support aliasing commands just yet.. Closing this for now.

**Pull request closed without merging**
