### PR TITLE
Add info & open commands

### PR DESCRIPTION
**Pull request by satazor**
This implements #4 

Improvements:
- Simplify folder structure
- Add better error output when a request or other error happens
- Exit with code 1 if an error happens
- Fix `-o json` for the search command

### CODE REVIEW

**Comment by satazor** [comment]
@flesch can you review this out? I got one question for you: why is the JSON.parse + JSON.stringify necessary [here](https://github.com/npms-io/npms-cli/blob/master/bin/cmd/search.js#L44)?

**Comment by flesch** [comment]
JSON.stringify will remove any undefined keys, so it was just a simple way of getting rid of any of those that weren't defined.

**Comment by satazor** [comment]
@flesch I think that we can remove that because `got` is calling JSON.stringify under the hood that will remove those keys.

**Comment by flesch** [comment]
Oh, nice.

The other changes look good too!

**Comment by satazor** [comment]
@flesch you are right, it is necessary! Going to squash + merge this an release a new version, is that ok?

**Comment by flesch** [comment]
Sounds good!

**Comment by satazor** [comment]
@flesch Done!

I also have noticed that the table output doesn't quite adjust for small sized terminal windows. Can that be fixed?

**Pull request merged**
